### ISSUE TITLE
"finish" event propagation bug

### ISSUE THREAD

**Issue by klyngbaek** [maxogden/multiplex#19]
When calling end() on a client side stream, the "finish" should not be emitted on the server side -- it currently is (when an on "data" listener is applied on the server).

Calling end() on the client indicates no more data to be written from the client to the server. Calling end() end on the client should not cause a "finish" event to be emitted on the server. [A "finish" event indicates that you can no longer write to a stream](https://nodejs.org/api/stream.html#stream_event_finish). A "finish" event should only by emitted on the server when we no longer want to write data from the server to the client. This is because multiplex supports full duplex streams. Calling end() in one direction (e.g. on the client), should not stop you from being able to send data the other way (e.g. sending data from server to client).

The following example illustrates this bug. A full duplex stream is opened between server and client. Data is sent from server to client, but when client calls end(), it stops data transfer from server to client. It should only be stopping data transfer from client to server.

```js
var multiplex = require('multiplex');
var plex1 = multiplex();
var stream1 = plex1.createStream();


////////////////////////////////////////////////////////////////////////////////
// server side
////////////////////////////////////////////////////////////////////////////////
var plex2 = multiplex(function onStream(stream, id) {
  
  stream.on('error', function(error) {
    console.log(error);
  });

  stream.on('finish', function() {
    console.log('Client stream emits "finish" event -- this should not happen');
  });


  // commenting this block out makes it work, wierd!
  stream.on('data', function(c) {
    console.log('Client received: ' + c.toString());
  });


  setInterval(function () {
    console.log('Client tries to send data: yo');
    stream.write('yo');
  }, 200);

});


////////////////////////////////////////////////////////////////////////////////
// client side
////////////////////////////////////////////////////////////////////////////////

setTimeout(function() {
    console.log('Server calls end()');
    stream1.end('some_end_data_from_server');
}, 1000);

stream1.on('error', function(err) {
    console.log(err);
});

stream1.on('data', function(data) {
    console.log('Server received data from client: ' + data.toString());
});


////////////////////////////////////////////////////////////////////////////////
// pipe the client server together
////////////////////////////////////////////////////////////////////////////////
plex1.pipe(plex2).pipe(plex1);
```

**Comment by mafintosh** [comment]
similar to the `net` module, multiplex streams per default don't allow half open mode (what you are describing above). you can enable this though by setting `halfOpen: true` in the multiplex constructor

``` js
var plex = multiplex({halfOpen: true}, onStream)
```

let me know if that works

**Comment by klyngbaek** [comment]
That did the trick, thanks! 😀
