### ISSUE TITLE
Pass in any object to `destroy` method?

### ISSUE THREAD

**Issue by klyngbaek** [maxogden/multiplex#23]
It looks like the current `destroy` method only accepts an `Error` object. Would it make sense for the `destroy` method to accept any object instead of a strictly an `Error` object?

Thanks in advance.

**Comment by mafintosh** [comment]
Normally streams don't support this so I'm not sure its a good idea :) Whats the use-case?

**Comment by klyngbaek** [comment]
No specific use case. I'm trying to support the existing unit tests of [dataplex](https://github.com/substack/dataplex), and non-error errors was one of the test cases. It sounds like this is behavior that does not have to be supported. Thanks.
