### ISSUE TITLE
What is the motivation for the different behaviors of stream.end() and stream.destroy()?

### ISSUE THREAD

**Issue by yaronyg** [maxogden/multiplex#29]
``` node
var mux =  multiplex(function () {

});
var stream = mux.createStream();
stream.on('finish', function () {
  console.log("We are finish");
});
stream.on('close', function () {
  console.log("We are closed");
});
stream.end();
```

I would have expected that this code would print both "We are finish" and "We are closed". But in fact, it only prints "We are finish". There never seems to be a close event emitted on the stream.

If I change stream.end() to stream.destroy() then I get the opposite behavior, "We are closed" is printed but not "We are finish".

This was tested with 6.7.0.

**Comment by mafintosh** [comment]
.destroy is there so you can indicate a non-graceful shutdown. `finish` and `end` are not guaranteed to emit unless both the writeable and readable part of the stream is completely flushed.
